meta_product_name: "Foenix Coding"
meta_title: "Foenix Coding | Coding and Marking made easy"
meta_description: "FX ONE is a plug-and-play Industrial inkjet Printers for all types of production lines."
meta_keywords: “coding marking, Foenix printer, industrial marking, industrial inkjet, case coding and marking, product coding and marking, inkjet coding and marking, date printing, lot number printer, barcode printer"
meta_image: "meta_image.png"
twitter_account: "@foenix_coding"
